Cargo.lock, Cargo.toml, crates/api/Cargo.toml, crates/api/src/error.rs, crates/api/src/lib.rs
Please review this as the error type to be implemented in the kitsune2 external api. (and potentially for internal module traits if we so choose).
Once this PR is merged, I will go through the existing code implementing its use.
=> K2Error Type

Cargo.lock, Cargo.toml, crates/api/Cargo.toml, crates/api/src/agent.rs, crates/api/src/lib.rs, crates/api/src/url.rs, crates/core/src/factories/mem_peer_store/test.rs
In starting work on the transport module, I've discovered that we need a real Url type. String isn't gonna cut it anymore : )
=> Need a Real Url Type

crates/api/src/agent.rs, crates/api/src/arc.rs, crates/api/src/lib.rs, crates/api/src/peer_store.rs, crates/core/src/factories/mem_peer_store.rs, crates/core/src/factories/mem_peer_store/test.rs
It's worth a quick scan to see what is moved vs new before digging into the code. However, what has moved has also changed due to a changed definition of the arc. See https://github.com/holochain/kitsune2/pull/48#discussion_r1876541143
=> BasicArc convert to type

crates/dht/art/dht-circle.svg, crates/dht/art/dht-graph.svg
Took my own stab at these.
I wanted them to have the same number of time slices back to the origin, a little more separation between the segments, and labels on both diagrams to more easily relate them.
=> DHT Docs--Alternate Svg Options

crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/core_fetch/test/incoming_response_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/core/src/factories/core_space/test.rs, crates/core/tests/fetch.rs, crates/test_utils/src/lib.rs
I hope tests will be steady now on Windows.
=> fix(core): increase timeouts in fetch tests to prevent flakiness

Cargo.lock, crates/api/src/bootstrap.rs, crates/api/src/builder.rs, crates/api/src/config.rs, crates/api/src/fetch.rs, crates/api/src/gossip.rs, crates/api/src/kitsune.rs, crates/api/src/local_agent_store.rs, crates/api/src/op_store.rs, crates/api/src/peer_meta_store.rs, crates/api/src/peer_store.rs, crates/api/src/space.rs, crates/api/src/transport.rs, crates/core/Cargo.toml, crates/core/src/factories/core_bootstrap.rs, crates/core/src/factories/core_bootstrap/test.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_gossip.rs, crates/core/src/factories/core_kitsune.rs, crates/core/src/factories/core_local_agent_store.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/core_space/test.rs, crates/core/src/factories/mem_bootstrap.rs, crates/core/src/factories/mem_op_store.rs, crates/core/src/factories/mem_peer_meta_store.rs, crates/core/src/factories/mem_peer_store.rs, crates/core/src/factories/mem_transport.rs, crates/gossip/src/gossip.rs, crates/transport_tx5/src/lib.rs, crates/transport_tx5/src/test.rs
RESOLVES: https://github.com/holochain/kitsune2/issues/83
=> Config Validation

crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs
Before the test didn't make it through 200 iterations. Now 1000 iterations won't break it =)
=> test(core): fix test requests_are_dropped_when_max_back_off_expired in core_fetch

Cargo.lock, crates/dht/Cargo.toml, crates/dht/src/dht.rs, crates/dht/src/dht/snapshot.rs, crates/dht/src/dht/tests.rs, crates/dht/src/dht/tests/harness.rs, crates/gossip/Cargo.toml, crates/gossip/src/gossip.rs, crates/gossip/src/lib.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/disc_sectors_diff.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/update.rs
Deals with a gap from the previous PR about integrating the DHT model into gossip. The model needs to be updated every `UNIT_TIME`.
To facilitate testing this change, I've put the DHT model behind a trait. I don't love that change but for the sake of testing, it's justifiable I think.
=> Add dht update task

crates/dht/src/dht.rs
Follow up for https://github.com/holochain/kitsune2/pull/101
=> Do less work when the byte limit is exhausted after finding a DHT diff

Cargo.lock, Cargo.toml
Release today's changes for use in Holochain
=> chore: Bump versions for publish

Cargo.lock, crates/dht/src/arc_set.rs, crates/gossip/Cargo.toml, crates/gossip/src/protocol.rs, crates/gossip/src/respond/harness.rs, crates/gossip/src/respond/initiate.rs
Not much changing here, just adding more tests for the initiate responder
=> More initiate tests

crates/api/README.md, crates/bootstrap_srv/README.md, crates/core/README.md, crates/dht/README.md, crates/gossip/README.md, crates/kitsune2/README.md, crates/kitsune2_showcase/README.md, crates/transport_tx5/README.md
=> docs: Add READMEs

Cargo.lock, Cargo.toml, Makefile, crates/bootstrap_srv/Cargo.toml, crates/bootstrap_srv/src/bin/kitsune2-bootstrap-srv.rs, crates/bootstrap_srv/src/config.rs, crates/bootstrap_srv/src/http.rs, crates/bootstrap_srv/src/lib.rs, crates/bootstrap_srv/src/sbd.rs, crates/bootstrap_srv/src/server.rs, crates/bootstrap_srv/src/test.rs
Support running the SBD signalling service in the same process as the bootstrap server
=> feat: Support SBD in bootstrap

.github/workflows/bootstrap.yaml, .github/workflows/test.yaml, Dockerfile, crates/bootstrap_srv/src/bin/kitsune2-bootstrap-srv.rs, crates/bootstrap_srv/src/http.rs, crates/bootstrap_srv/src/test.rs, crates/core/src/factories/core_space.rs, crates/kitsune2_showcase/src/main.rs
Docker container for the bootstrap server. Currently deployed at `https://bootstrap2.holochain.org`.
We will have to actually start tagging our releases to produce bootstrap a container for each release.
=> Add docker container

crates/bootstrap_srv/src/http.rs, crates/bootstrap_srv/src/test.rs, crates/bootstrap_srv/src/tls.rs
=> feat: Reload TLS certificates

crates/api/src/kitsune.rs, crates/core/src/factories/core_kitsune.rs, crates/core/src/factories/core_space/test.rs
Need some additional space accessors on the kitsune type to do the preflight sending agent infos thing.
=> space accessors

crates/dht/src/time.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/agents.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/disc_sectors_diff.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/no_diff.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/respond/terminate.rs, crates/gossip/src/timeout.rs
Makes K2 gossip easier to debug by adding more trace logging
=> Gossip improvements

Cargo.lock, Cargo.toml
Release the metrics/stats dumping
=> chore: Publish 0.0.1-alpha.14

crates/core/src/factories/core_space.rs, crates/core/src/factories/core_space/test.rs, crates/gossip/src/storage_arc.rs
=> feat: Broadcast agent info when declaring a new storage arc

crates/api/src/op_store.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/test/incoming_response_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/core/src/factories/mem_op_store.rs
=> feat(core): filter out requests for ops that are already in the store

crates/gossip/proto/gen/kitsune2.gossip.rs, crates/gossip/proto/gossip.proto, crates/gossip/src/gossip.rs, crates/gossip/src/respond/harness.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/terminate.rs, crates/gossip/src/state.rs
=> feat(kitsune2_gossip): Resolve conflicting initiates

crates/api/src/transport.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/core_fetch/test/incoming_response_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/core/src/factories/core_publish.rs, crates/core/src/factories/core_publish/test.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/mem_transport.rs, crates/core/tests/fetch.rs, crates/gossip/src/config.rs, crates/gossip/src/gossip.rs, crates/gossip/src/harness.rs, crates/gossip/src/initiate.rs, crates/gossip/src/respond.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/harness.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/timeout.rs
Closes #177
This PR has created some flaky tests. The cause will be resolved by #182, so that should be merged before this one
=> Initiate faster after failure

Cargo.lock, Cargo.toml
This includes the datachannel android vendor fix.
=> bump tx5 and k2 version

.github/workflows/test.yaml, Cargo.lock, Cargo.toml, crates/core/Cargo.toml, crates/core/src/factories/core_bootstrap.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_publish.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/mem_bootstrap.rs, crates/core/src/factories/mem_peer_store.rs, crates/gossip/Cargo.toml, crates/gossip/src/config.rs, crates/kitsune2/Cargo.toml, crates/kitsune2/examples/schema.rs, crates/kitsune2_showcase/src/app.rs, crates/transport_tx5/Cargo.toml, crates/transport_tx5/src/lib.rs
Part of https://github.com/holochain/holochain/issues/4894
A lot of the content here is the example. I've added that to CI in a bit of an untidy way with a view to merging that with the `cargo make` PR.
=> feat: Add schema support for configuration

Cargo.lock, Cargo.toml, crates/kitsune2_showcase/src/app.rs, crates/transport_tx5/Cargo.toml, crates/transport_tx5/src/lib.rs
backport of https://github.com/holochain/kitsune2/pull/202
=> moar tx5 config 0.1 backport

.github/workflows/test.yaml, Makefile, Makefile.toml, crates/api/Makefile.toml, crates/bootstrap_client/Makefile.toml, crates/bootstrap_srv/Makefile.toml, crates/core/Makefile.toml, crates/dht/Makefile.toml, crates/gossip/Cargo.toml, crates/gossip/Makefile.toml, crates/gossip/src/harness/op_store.rs, crates/gossip/src/storage_arc.rs, crates/kitsune2/Makefile.toml, crates/kitsune2_showcase/Makefile.toml, crates/test_utils/Makefile.toml, crates/tool_proto_build/Makefile.toml, crates/transport_tx5/Makefile.toml
=> chore: Add cargo make

crates/api/src/fetch.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs
Part of https://github.com/holochain/kitsune2/issues/220
=> feat: Notify on fetch queue drained

Cargo.lock, crates/api/src/gossip.rs, crates/gossip/Cargo.toml, crates/gossip/src/config.rs, crates/gossip/src/gossip.rs, crates/gossip/src/harness.rs, crates/gossip/src/initiate.rs, crates/gossip/src/summary.rs, crates/gossip/tests/historical_load.rs, crates/gossip/tests/initial_sync.rs, crates/test_utils/src/agent.rs
Closes https://github.com/holochain/kitsune2/issues/220
Depends on #227
=> Faster initiate

crates/api/src/transport.rs, crates/core/src/factories/core_space.rs, crates/transport_tx5/src/lib.rs, crates/transport_tx5/src/test.rs
Addresses https://github.com/holochain/kitsune2/issues/221
May need additional integration tests at the holochain level with an actual peer meta store implementation.
=> Record peer connection failures in the peer meta store

crates/gossip/src/initiate.rs, crates/gossip/src/peer_meta_store.rs
=> Filter unresponsive peers in gossip

CHANGELOG.md
Add a changelog for all versions that are part of the `main` branch. Note that this means there are no entries for versions `v0.1.6`, `v0.1.7`, `v0.1.8`, nor `v0.1.9` because they are not part of this branch.
=> docs: add a changelog

crates/api/src/id.rs
Part of https://github.com/holochain/holochain/issues/5163
I'm pretty sure that most implementations on top of Kitsune2 will actually need different logic for op ids than other ids. I'm trying to make the API change compatible so it can be backported right back to 0.1 of K2 and used in Holochain 0.5.
Note that because of the statics, there are no tests for this code and I've not attempted to add any as part of this PR.
=> chore: Allow a dedicated override for `OpId`

crates/api/src/agent.rs, crates/api/src/doc/agent.rs, crates/bootstrap_client/src/lib.rs, crates/bootstrap_client/tests/integration.rs, crates/bootstrap_srv/src/lib.rs, crates/bootstrap_srv/src/parse.rs, crates/bootstrap_srv/src/server.rs, crates/bootstrap_srv/src/test.rs, crates/core/src/factories/core_bootstrap.rs, crates/core/src/factories/core_bootstrap/test.rs, crates/core/src/factories/core_publish/test.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/mem_bootstrap/test.rs, crates/test_utils/src/agent.rs
Addresses https://github.com/holochain/kitsune2/issues/275 (partially reverts #273)
=> fix: revert renaming of space field in AgentInfo
