holochain/kitsune2

.github/workflows/test.yaml, Cargo.lock, Cargo.toml, Makefile, crates/bootstrap_srv/Cargo.toml
The complete boostrap server branch is rather large. Breaking out the dependencies needed and some unrelated CI tooling changes so the actual server pull requests can be reviewed with more focus.
- See the follow on [Core #10](https://github.com/holochain/kitsune2/pull/10) for the core implementation code of the server.
- See the follow on [Testing #11](https://github.com/holochain/kitsune2/pull/11) PR for api endpoint tests and general notes about this effort in the PR description.
=> Kitsune2 Bootstrap Server--Preparation

crates/api/src/agent.rs
Heh, I should have searched for uses of std::io::Error before not including this [in the previous pr](https://github.com/holochain/kitsune2/pull/8), but in any case: here is implementing the usage of K2Error in the existing code in this repo.
=> use K2Error in existing k2 code

crates/api/src/config.rs, crates/api/src/lib.rs
This is a greatly simplified version of the config pattern I had put in the kitsune spike, with the added benefit that modules can make public their config structs so they are available in rust docs for understanding how to use them.
@ThetaSinner - I was considering your request for runtime changeable configs and came to the conclusion that would be better handled via some other mechanism. Namely we could specify a `default_` prefixed version of that setting here in the immutable config, and then expose a function on the module api to update runtime settings.
I was just looking through the [current tuning params](https://docs.rs/kitsune_p2p_types/latest/kitsune_p2p_types/config/tuning_params_struct/struct.KitsuneP2pTuningParams.html) and started worrying about how poorly legacy kitsune …
=> simplified mvp module factory config pattern

Cargo.lock, crates/api/src/op_store.rs, crates/api/src/timestamp.rs, crates/dht/src/time.rs, crates/memory/Cargo.toml, crates/memory/src/op_store.rs, crates/memory/src/op_store/time_slice_hash_store.rs
Getting rid of the origin time means one less value that user has to understand and set. It was a limited value concept anyway because you have to set it to when you create the app so that everyone sees the value origin time. Then if somebody installs the app 6 months later then they have to gossip 6 months worth of empty hashes anyway.
This replaces the origin time concept with starting from the UNIX_TIMESTAMP (i.e. a 0 valued Timestamp, because that's how our Timestamp is defined). Any empty hashes are represented as a `(initial_time_slice_id, count)` pair.
So for a network with a slice period of 1 week, that might look something like:
- UNIX timestamp, through to 3 weeks ago, no data stored
- 3 weeks ago to 2 weeks ago, a combined hash stored
- 2 weeks ago to 1 week ago, a combined …
=> Eliminate the origin time

Cargo.lock, crates/api/src/agent.rs, crates/api/src/arc.rs, crates/api/src/lib.rs, crates/api/src/op_store.rs, crates/api/src/peer_store.rs, crates/core/src/factories/mem_peer_store.rs, crates/core/src/factories/mem_peer_store/test.rs, crates/dht/Cargo.toml, crates/dht/src/hash.rs, crates/dht/src/lib.rs, crates/dht/src/time.rs, crates/memory/src/op_store.rs, crates/memory/src/op_store/time_slice_hash_store.rs, crates/test_utils/src/lib.rs
Implements hash partitioning in terms of the existing time partitioning.
Things to pay particular attention to:
- The arc changes, looking at naming and whether we like the simple typesdefs vs structured types. E.g. `arc_contains` has to be defined as an associated function rather than a member method.
- The documentation on the hash space. It's a pretty significant deviation from how the hash space was managed in Kitsune2. My reasoning is that having the hash space change its partitioning is extra complexity and endless extra computation for little value. We can vary the argent size, so what really matters is just having small enough chunks that an agent covering one chunk is holding a small enough amount of data.
- All time slices are created up front, even if the combined agent arcs …
=> Dht hash partitioning

crates/api/src/transport.rs, crates/core/src/factories/mem_transport.rs, crates/core/src/factories/mem_transport/test.rs
Instead of `Transport` directly being a struct, use our trait+trait-object pattern for test-ability.
There is no functional change in this PR, it is purely moving code around + renaming.
=> Transport Trait

Cargo.lock, crates/api/src/fetch.rs, crates/api/src/op_store.rs, crates/core/Cargo.toml, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/message_handler.rs, crates/core/src/factories/core_fetch/test.rs, crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/mem_op_store.rs, crates/core/src/factories/mem_op_store/test.rs, crates/dht/src/dht/tests.rs, crates/dht/src/dht/tests/harness.rs, crates/dht/src/hash.rs, crates/dht/src/time.rs
The op store should ingest only op data. Hashes should be computed when data arrives so that we aren't trusting somebody else to do our hashing. The rest of this PR is consequences from trying to achieve that.
Within the op store, we want to be able to store more fields than the op contains. Like `stored_at` which I'm using on the gossip PR for incremental sync. That means we need to keep the op data model and the model the op store uses internally as separate types.
The big fiddle here was that I couldn't use the hash function that was added with the fetch queue inside the mem op store without destroying the DHT tests. Those need predictable IDs to get the ops into different parts of the DHT to test the location logic. I could spend time trying to find op data that places the ops in the …
=> Op store split metadata

crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/back_off.rs, crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs
Adds a configurable delay to fetch request queue (as it says above), which passes before re-inserting a just sent request back into the outgoing request queue.
=> refactor(core): add configurable delay to fetch request queue

crates/api/src/fetch.rs, crates/api/src/gossip.rs, crates/api/src/id.rs, crates/api/src/op_store.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/back_off.rs, crates/core/src/factories/core_fetch/test.rs, crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/core_fetch/test/incoming_response_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/core/src/factories/core_gossip.rs, crates/core/src/factories/core_gossip/test.rs, crates/gossip/src/gossip.rs
Most of this is renaming because the gossip isn't working with `AgentId`s, it's working with `Url`s.
When we gossip, we aren't gossiping with a single agent. I could list all peers and map a peer url back to an agent id... but then that agent might move and just because we can use the agent id to look up a peer url, that doesn't mean it's the right one.
On the other hand, when we store a peer url, there's no guarantee that the URL stays valid.
I think it's slightly better to fetch from a specific node by its `Url` and have to drop requests if that peer isn't handing us back ops, than it is to track by agent id which may or may not provide a Url that has the ops we originally discovered.
=> Integrate fetch with gossip

Cargo.lock, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/back_off.rs, crates/core/src/factories/core_fetch/message_handler.rs, crates/core/src/factories/core_fetch/test.rs, crates/core/src/factories/core_fetch/test/incoming_request_queue.rs, crates/core/src/factories/core_fetch/test/incoming_response_queue.rs, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/core/src/factories/core_space/test.rs, crates/core/tests/fetch.rs, crates/test_utils/Cargo.toml, crates/test_utils/src/agent.rs, crates/test_utils/src/id.rs, crates/test_utils/src/lib.rs, crates/test_utils/src/space.rs
Adds two integration tests of the fetch module:
* One simple happy test of a recent gossip kind
* One where one peer isn't online at first and put on back-off, then comes online and fetch succeeds
More suggestions?
Also removes peer store from other tests.
resolves #65
=> Add core fetch integration tests

Cargo.lock, Cargo.toml, crates/core/src/factories/core_fetch/test/outgoing_request_queue.rs, crates/transport_tx5/Cargo.toml, crates/transport_tx5/src/lib.rs, crates/transport_tx5/src/test.rs
I've ignored the `peer_connect_disconnect` test due to the following issue: https://github.com/holochain/tx5/issues/119. I think that issue may be a low-ish priority, since we don't yet have any logic that depends on the disconnect events/callbacks.
=> Tx5Transport Module

crates/api/src/op_store.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/mem_op_store.rs, crates/dht/src/arc_set.rs, crates/dht/src/dht.rs, crates/dht/src/dht/snapshot.rs, crates/dht/src/hash.rs, crates/gossip/README.md, crates/gossip/proto/gen/kitsune2.gossip.rs, crates/gossip/proto/gossip.proto, crates/gossip/src/gossip.rs, crates/gossip/src/initiate.rs, crates/gossip/src/protocol.rs, crates/gossip/src/state.rs, crates/gossip/src/timeout.rs
Integrates the DHT model into gossip to the extent that a tests can be written for disc sync and ring sync.
Most of the required messages are in place now. We might want a "busy" message depending how we deal with limiting the number of rounds or updating the DHT model. We might also want a "Terminate" message to deal with errors so we make an effort to avoid forcing the other side to time out when something goes wrong that wasn't their fault.
There are a lot of paths here that can't be tested in an integration test because they require DHT model mismatches (updated at different timestamps) that happen during the sync process. I need to add unit tests to cover these cases but the PR is big enough I think.
I've not dealt with updating the state of the DHT model. We can either do that in a …
=> Integrate dht model

crates/api/src/op_store.rs, crates/core/src/factories/mem_op_store.rs, crates/core/src/factories/mem_op_store/test.rs, crates/dht/src/arc_set.rs, crates/gossip/src/respond.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/initiate.rs
This is another hopefully straight forward change. Requesting "what's new" should respect the common arc set during gossip in the same way that the DHT diff does. We wouldn't notice this right now with full arc but I think it's best to have this in place.
=> New ops respect common arc set

crates/api/src/op_store.rs, crates/core/src/factories/mem_op_store.rs, crates/dht/src/dht.rs, crates/dht/src/dht/tests.rs, crates/dht/src/dht/tests/harness.rs, crates/dht/src/time.rs, crates/gossip/proto/gen/kitsune2.gossip.rs, crates/gossip/proto/gossip.proto, crates/gossip/src/gossip.rs, crates/gossip/src/initiate.rs, crates/gossip/src/respond.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/disc_sectors_diff.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/state.rs
Applies the same logic that we have for "new ops" to the op ids returned by the DHT diff process. I believe this is necessary regardless of whether it's a complete solution to the "new agent joining an existing network" problem.
By leaving this unlimited, we'd just return the entire data set in one batch during the first gossip round with new peers. That's too much load on the peer you happen to hit. As I'm writing, I'm wondering if we should enforce a maximum value for this that peers can request...
By limiting how much data we get in one go, we aren't doing anything too complicated like trying to decide which sectors we want data from or which time slices, when both are sparse and we'd get unpredictable results that way. Like this, we do our best to sync. Then we have to hope that …
=> Limit data sent after dht differences

.github/workflows/test.yaml, Cargo.lock, Cargo.toml, crates/api/src/builder.rs, crates/api/src/gossip.rs, crates/api/src/space.rs, crates/core/Cargo.toml, crates/core/src/factories/core_bootstrap/test.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/message_handler.rs, crates/core/src/factories/core_gossip.rs, crates/core/src/factories/core_kitsune.rs, crates/core/src/factories/core_local_agent_store.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/core_space/test.rs, crates/gossip/src/gossip.rs, crates/kitsune2/Cargo.toml, crates/kitsune2/src/lib.rs, crates/test_utils/Cargo.toml, crates/test_utils/src/bootstrap.rs, crates/test_utils/src/lib.rs, crates/test_utils/src/noop_bootstrap.rs, crates/transport_tx5/Cargo.toml
Adds a top-level crate called "kitsune2" with a production default builder. There's a full integration test using the builder.
The test is flaky with higher number of ops. ~~and I'm asking here first before going about the debugging myself. When the number of ops to be exchanged during gossip is increased to about 100 each, the following error happens almost always:~~
Fixing the error will be part of another branch.
```sh
2025-01-28T18:37:32.101834Z DEBUG NETAUDIT: pub_key=0HDL-1H_0bmwwx7XZUWY6k39pRM9OSHLWwIs_P2c6xE byte_count=195 err=Kind(BrokenPipe) m="tx5-connection" a="send_framed_error"
2025-01-28T18:37:32.101862Z  WARN kitsune2_core::factories::core_fetch: could not send ops to requesting peer: tx5 send error (src: broken pipe) op_ids=[qLkchkQ6c3wdv8e8z2edk6OAjSQFbHIEwMr7vXYiEfM] …
```
=> feat(kitsune2): add top-level crate kitsune2

crates/core/src/factories/mem_op_store.rs, crates/dht/src/dht/tests.rs, crates/gossip/src/gossip.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/initiate.rs
Tests the previous PR -> https://github.com/holochain/kitsune2/pull/94
Some minor improvements needed in the mem peer store to support this change, I'll comment on those separately.
I think this raises an important problem though. I still want these tests in but I think I should change how I've applied limits. It shouldn't apply in the middle of a time slice because if a time slice grows larger than the limit, we'll never be able to sync it. So I think I should roll back the code that applies limits in the op store and does a soft application of the limit in the DHT code that calls the op store. That way we might return more op ids than the other side wanted but we won't get stuck on a time slice. It's an edge case really, for when there's more data around, but I think it's easier to fix …
=> Op data limit tests

crates/api/src/op_store.rs, crates/core/src/factories/mem_op_store.rs, crates/dht/src/dht.rs, crates/dht/src/time.rs, crates/gossip/src/gossip.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/state.rs
This one is slightly subtle. I initially applied the limit rather harshly at an "op boundary". If this falls within a really large sector/slice then it's possible that the limit isn't set high enough to ever retrieve that data. I think it's better to be less strict with the limit to ensure we always make progress when gossiping a diff.
The changes on this PR are all a fallout from that change.
=> Limit op data at sector granularity

crates/api/src/arc.rs, crates/dht/src/arc_set.rs, crates/dht/src/dht/snapshot.rs, crates/gossip/Cargo.toml, crates/gossip/src/gossip.rs, crates/gossip/src/lib.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/storage_arc.rs
The meat of this is the update algorithm. I've done my best to keep it logical and well-commented.
Basically, we're trying to start from the common arc set and skip any mismatched sectors. Then we see if merging the matching sectors into our storage arc yields a longer arc that covers the existing one. Starting from an empty arc is treated as a special case. It took me hours of thinking to put that together so I've done by best to comment and test clearly!
The integration is also interesting. If we get a ring diff then we can update our arc because we know the disc is synced and we can examine the ring diff to see what sectors are matching. That's pretty sound logic I think, but we won't necessarily get a ring diff because the "what's new" operation will keep some agents in sync without a …
=> Update storage arcs

Cargo.toml
`kitsune2_api` won't build inside Holochain because we pin serde in HSB. We just need to not request a specific version of serde. We only actually depend on the 1.0 API not anything added in recent versions.
=> chore: Pick serde version that is more widely compatible

crates/api/src/peer_meta_store.rs, crates/core/src/factories/mem_peer_meta_store.rs, crates/core/src/factories/mem_peer_meta_store/test.rs, crates/gossip/src/gossip.rs, crates/gossip/src/initiate.rs, crates/gossip/src/peer_meta_store.rs, crates/gossip/src/respond/harness.rs
This was a mistake I think, it's already in the context of a space and doesn't need to keep data separate by space
=> Peer meta store no space

Cargo.lock, crates/gossip/Cargo.toml, crates/gossip/README.md, crates/gossip/proto/gen/kitsune2.gossip.rs, crates/gossip/proto/gossip.proto, crates/gossip/src/error.rs, crates/gossip/src/gossip.rs, crates/gossip/src/lib.rs, crates/gossip/src/peer_meta_store.rs, crates/gossip/src/protocol.rs, crates/gossip/src/respond.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/agents.rs, crates/gossip/src/respond/busy.rs, crates/gossip/src/respond/disc_sector_details_diff.rs, crates/gossip/src/respond/disc_sector_details_diff_response.rs, crates/gossip/src/respond/disc_sectors_diff.rs, crates/gossip/src/respond/hashes.rs, crates/gossip/src/respond/initiate.rs, crates/gossip/src/respond/no_diff.rs, crates/gossip/src/respond/ring_sector_details_diff.rs, crates/gossip/src/respond/ring_sector_details_diff_response.rs, crates/gossip/src/respond/terminate.rs, crates/gossip/src/timeout.rs
- Adds a new error type so that we can tell the difference between errors that happened locally (can't access our op store or clock is set wrong etc) and errors that were caused by the peer not following the protocol.
- Terminates gossip rounds that cannot proceed for errors that might be recoverable. For example, running into a logic error with a disc diff should not prevent recent ops and agents from syncing, so we don't need to error and close the connection. Similarly if we found a disc diff but the diff is resolved by the time we do the disc details diff, we don't need to error and close the connection. In these cases, we terminate to be nice to the other side and not force them to time out.
- Based on the improved error handling, adds several new peer meta values
Contributes to #42
=> Add more peer meta for gossip

Cargo.lock, Cargo.toml, crates/bootstrap_client/Cargo.toml, crates/bootstrap_client/README.md, crates/bootstrap_client/src/lib.rs, crates/bootstrap_client/tests/connect.rs, crates/bootstrap_srv/src/server.rs, crates/bootstrap_srv/src/test.rs, crates/core/Cargo.toml, crates/core/src/factories/core_bootstrap.rs
Adds a new bootstrap client crate. Extracted the bootstrap PUT and GET calls from core and we'll be able to re-use this crate in Holochain where we connect to the bootstrap server for debug purposes.
=> Add bootstrap client

Cargo.lock, Cargo.toml, Makefile
Includes switching back from edition 2024 to 2021, and the new bootstrap client
=> chore: Bump versions to alpha4

.github/workflows/test.yaml, flake.lock, flake.nix
These systems are supported by consuming nix flakes, so they had to be added here.
=> build(nix): add systems x86_64-darwin and aarch64-linux

crates/api/src/op_store.rs, crates/core/src/factories/mem_op_store.rs, crates/dht/src/dht.rs, crates/dht/src/hash.rs, crates/dht/src/time.rs
I knew this was doing a lot of work on startup until the first full time slice hash was computed but it turns out, it's a silly amount of work. Tests in `holochain_p2p` were taking 45s when they only need to take 0.2s. 
We already avoid recomputing earlier full slice hashes if we have a stored count. We also avoid recomputing partial slice hashes if we already know their value. However, we were spending a lot of initialisation time on computing slice hashes from the `UNIX_TIMESTAMP` that we can easily rule out by bounding the start time of the query.
Before I got this set up right, the exists tests did a lot of complaining... so I think they are sufficient. This doesn't add any new logic or states, it's just avoiding work. So if everything that worked before still works then we're good. …
=> Avoid computing hashes for empty slices

Cargo.lock, crates/api/src/transport.rs, crates/core/src/factories/mem_transport.rs, crates/transport_tx5/Cargo.toml, crates/transport_tx5/src/lib.rs, crates/transport_tx5/src/test.rs
Adds `dump_network_stats` to the `Transport`
For datachannel, the output looks like:
```json
{
"backend": "backendLibDataChannel",
"peerUrlList": [
"ws://127.0.0.1:43427/_78iVW071_gH59btIMxrWnOuUZS8kbVAhdR3DkiV4A4"
],
"connectionList": [
{
"pubKey": "anhRG-p_Myjf6SWobMF0Sujajiqb_1Pw_jifQkaMN7U",
"sendMessageCount": 2,
"sendBytes": 10,
"recvMessageCount": 2,
"recvBytes": 10,
"openedAtS": 1742574018,
"isWebrtc": true
}
]
}
```
Note the transform of the `pubKey` field in the `connectionList`. I think that's good enough to let the end user list agents and join the stats output as desired, rather than doing the join automatically like we used to.
=> feat: Add `dump_network_stats` to the transport

crates/api/src/fetch.rs, crates/api/src/gossip.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_fetch/back_off.rs, crates/core/src/factories/core_gossip.rs, crates/gossip/src/gossip.rs, crates/gossip/src/lib.rs, crates/gossip/src/summary.rs
Contributes to #95 but adding state dumps for fetch and gossip. The gossip dump optionally includes a rather detailed DHT dump.
Note that dumping the DHT state one segment at a time would make it easier to compare. We might want to consider making that change when we go to sharding. But for now, the arc is either going to empty and the summary will be too or it'll be full and splitting by segment is a little pointless.
=> feat: Add state dumps for fetch and gossip modules

crates/api/src/fetch.rs, crates/api/src/kitsune.rs, crates/core/src/factories/core_kitsune.rs
If we want to be able to get network stats, we need to access the `Transport` instance that Kitsune is using
=> feat: Expose the transport from the `Kitsune` trait

crates/api/src/transport.rs, crates/core/src/factories/mem_transport.rs, crates/transport_tx5/src/lib.rs, crates/transport_tx5/src/test.rs
Exposes tx5 network stats as typed. I hadn't looked closely enough to realize that the stats are constant and the backend is just a field to tell you what's loaded. 
To give us a little isolation to tx5 changes and let me make the format a bit friendlier (pubkey as bytes makes it less obvious that it's also in the URL), I've made this  a kitsune2_api type. That also means that Holochain doesn't have to put tx5 types in its API.
=> feat: Make network stats typed

crates/api/src/space.rs, crates/core/src/factories/core_space.rs
I believe when this was added, the local agent store wasn't exposed through the space. Now that it is, this isn't useful.
=> chore: Remove `get_local_agents` from the space API

.github/workflows/test.yaml, Cargo.lock, Cargo.toml
The integration into Holochain is nearing completion. It's looking like Kitsune2 is ready to be used at this point and we can commit to a proper version number.
=> chore: Update to 0.1.0

crates/core/src/factories/mem_op_store.rs
This was creating a test problem where ops received multiple times were not removed from the request queue, so would be requested indefinitely.
=> refactor(core)!:process_incoming_ops in MemOpStore returns all op ids

Cargo.lock, Cargo.toml, crates/gossip/Cargo.toml, crates/gossip/src/config.rs, crates/gossip/src/gossip.rs, crates/gossip/src/initiate.rs
This is really only an experience enhancement. The first round might fail, or on a larger network there should be peers finding you and initiating gossip fairly quickly.
On smaller networks, this helps get gossip started a bit quicker.
=> feat: Initiate first gossip round faster

crates/api/src/local_agent_store.rs, crates/api/src/space.rs, crates/core/src/factories/core_fetch.rs, crates/core/src/factories/core_local_agent_store.rs, crates/core/src/factories/core_space.rs, crates/core/src/factories/mem_op_store.rs, crates/dht/src/dht.rs, crates/gossip/src/gossip.rs, crates/gossip/src/harness.rs, crates/gossip/src/harness/op_store.rs, crates/gossip/src/respond/accept.rs, crates/gossip/src/respond/no_diff.rs, crates/gossip/src/timeout.rs, crates/gossip/tests/historical_load.rs, crates/test_utils/src/lib.rs
I think this is a more useful way of doing the check. The local agent we're sending to might have left the space and won't be in the local agent store but we still want to avoid sending to ourselves. 
I started looking at why the historical sync test was flaky. It turns out it was really not doing what it was supposed to do and I found some issues along the way. See the inline comments.
=> feat!: Expose current URL instead of is_local_agent

crates/bootstrap_srv/src/bin/kitsune2-bootstrap-srv.rs, crates/bootstrap_srv/src/server.rs
#131 
When the bootstrap server is embedded as a library, it currently prints the server address on startup, which is not desirable for library users.
=> refactor(bootstrap): move server address logging to binary

crates/kitsune2_showcase/src/app.rs
We've observed during testing that the Holo STUN servers are reporting unusable ICE candidates for some users. The Google STUN server does a much better job of getting people connected.
People are free to configure other WebRTC settings, but this is a more reliable default for development and testing.
=> chore: use Google STUN

rust-toolchain.toml
After switching to using `rustup` in the Nix devShell, in #213, the `rust-analyzer` from `rustup` is being invoked by my LSP. I don't see the harm in adding it as a component, but let me know if it causes problems and I'll just force my editor to use a different one.
=> chore: add rust-analyzer as a toolchain component

Cargo.lock, Cargo.toml, crates/bootstrap_srv/examples/test-auth-hook-server.rs
Bumps SBD to a version that doesn't double up the "authToken", and updates the auth test hook server to take a full ip:port so we can choose the interface it binds on.
=> bug fix and auth test binding change

crates/bootstrap_srv/src/sbd.rs
Apparently I missed one of these. Technically now that it's fixed, it is tested... in the sense that the server in no-hook mode was ignoring the correct header and not even running the token logic, and now will actually run it, and the tests pass.
It seems unlikely that somebody would somehow misspell this again in a future PR so it didn't seem worthy of a regression test, but let me know if you feel differently.
=> fix authorization

Cargo.toml, crates/api/Cargo.toml, crates/bootstrap_client/Cargo.toml, crates/bootstrap_srv/Cargo.toml, crates/core/Cargo.toml, crates/dht/Cargo.toml, crates/gossip/Cargo.toml, crates/kitsune2/Cargo.toml, crates/kitsune2_showcase/Cargo.toml, crates/test_utils/Cargo.toml, crates/tool_proto_build/Cargo.toml, crates/transport_tx5/Cargo.toml
According to the [manifset](https://doc.rust-lang.org/cargo/reference/manifest.html) it seems the `repository` field is preferable.  More explanation https://github.com/szabgab/rust-digger/issues/91
=> chore: Update Cargo.toml use repository instead of homepage

crates/gossip/src/storage_arc.rs
The function was renamed from `len` to `arc_span` but these calls were not updated because they are behind the `sharding` feature and so seem to not be tested.
=> fix: the sharding feature was using old function name

.github/workflows/test.yaml
PR to add a comment to this and future PRs to show what will be added to the generated changelog, including what version bump will happen due to these changes. See [the comment below](https://github.com/holochain/kitsune2/pull/254#issuecomment-3000465692) for an example.
=> ci: add job to generate changelog preview with git-cliff
